Add CircleCI option for key dealer
algolia/api-key-dealer pull request #18
Opened 2019-09-02 12:25 UTC by bsuravech

2019-09-12 08:51 UTC, nunomaduro reviewed
Sounds good overall. 

@bsuravech The commit of `blic/clients/algolia-keys` and ` public/clients/algolia-keys-mac` is intentional?

I will try to add some tests into this project. ( if is possible )

2019-09-12 08:51 UTC, nunomaduro commented on app/Http/Middleware/IsTravisRunning.php
> -        $repoOk = \in_array($orga, ['algolia', 'julienbourdeau']);
@julienbourdeau Is this fine?

2019-09-12 08:51 UTC, nunomaduro commented on client/src/buy.go
> -	TRAVIS_JOB_ID string
@julienbourdeau @aseure Can you validate this code in go?

2019-09-12 09:17 UTC, aseure requested changes
Just a small feedback on the Go part. Also on the form, perhaps this kind of PR could be split into smaller ones next time, since the changes and the reviewers are not related here.

Thank you for taking the time to contribute on this repo @bsuravech, it has been left alone for too long 😂

2019-09-12 09:17 UTC, aseure commented on client/src/buy.go
> +		CIRCLE_REPONAME:    string(os.Getenv("CI_PROJ_REPONAME")),
You can remove the `string( ... )` altogether, since `os.Getenv()` already [returns a string](https://golang.org/pkg/os/#Getenv).

2019-09-12 12:39 UTC, julienbourdeau commented on app/Http/Middleware/IsTravisRunning.php
> -        $repoOk = \in_array($orga, ['algolia', 'julienbourdeau']);
Yes, all good 👍

2019-09-12 12:46 UTC, julienbourdeau commented
@nunomaduro Clients binaries must be commited to be deployed. It's not the ideal but it's was easy for avoid having to push them somewhere or anything like that 👍

2019-09-12 13:04 UTC, julienbourdeau requested changes
Thank you for tackling this Betty 🙏 We're getting very close.

I think the Travis side of things is broken now. We can pair to finish the PR if you want. Overall, I'd like to get rid of the logic in the routing, and ensure that both travis and circleci still work. We'll probably get rid of both controllers and only keep the AlgoliaController 👍

2019-09-12 13:04 UTC, julienbourdeau commented on app/Http/Controllers/CircleciController.php
> +class CircleciController extends AlgoliaController
I don't see where this CircleCiController used?

2019-09-12 13:04 UTC, julienbourdeau commented on routes/web.php
> +if (env('CIRCLE_API_TOKEN')) {
As far as I understand, this will be part of the environment (heroku) so it will always be true. How do you use the travis middleware then? 🤔

2019-09-12 13:04 UTC, julienbourdeau commented on app/Http/Controllers/TravisController.php
> +class TravisController extends AlgoliaController
I feel like this travis controller is never called either

2019-09-12 13:04 UTC, julienbourdeau commented on routes/web.php
> +    'middleware' => $middleware,
I'd rather not have logic in the routing, that depends on the request. I think we can use the controller constructor instead.

2019-09-12 13:04 UTC, julienbourdeau commented on app/Http/Middleware/SetSource.php
> +        if (env('CIRCLE_API_TOKEN')) {
This should depend on something from the request, like `$request->has('CIRCLE_BUILD_NUM')`.

2019-09-13 13:05 UTC, julienbourdeau commented on client/src/buy.go
> +		CIRCLE_REPONAME:    string(os.Getenv("CI_PROJ_REPONAME")),
Thanks @aseure !

2019-09-13 13:29 UTC, merged